---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a VPC with 2 public and 2 private subnets (1 of each type in 2 AZs), 2 NAT instances for egress traffic, and a Bastion host beind an LB."

Parameters:

  VPCcidr:
    Type: String
    Description: "CIDR Block for the VPC."
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\/(\\d{1,2})"
    Default: "10.20.0.0/16"

  SNcidrs:
    Type: CommaDelimitedList
    Description: "Comma-delimited list of four CIDR blocks for the subnets (2 pub, 2 priv in diff AZs).  These must fall within the VPC CIDR block, and not overlap."
    Default: "10.20.0.0/24, 10.20.1.0/24, 10.20.2.0/24, 10.20.3.0/24"

  KeyPair:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Name of the KeyPair that will be used to connect to the instances"

  NATimage:
    Type: "AWS::EC2::Image::Id"
    Description: "NAT AMI ID"

  BastionImage:
    Type: "AWS::EC2::Image::Id"
    Description: "Bastion host AMI ID"

  MgmtIP:
    Type: "String"
    Description: "IP Address (not CIDR) for remote ssh access to NAT instances"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})"
    MinLength: 7
    MaxLength: 15

Resources:

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VPCcidr
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-vpc"

  Subnet1pub:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Sub "${AWS::Region}"
      CidrBlock: !Select
        - 0
        - !Ref SNcidrs
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sn1pub"

  Subnet1priv:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Sub "${AWS::Region}"
      CidrBlock: !Select
        - 1
        - !Ref SNcidrs
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sn1priv"

  Subnet2pub:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Sub "${AWS::Region}"
      CidrBlock: !Select
        - 2
        - !Ref SNcidrs
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sn2pub"

  Subnet2priv:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Sub "${AWS::Region}"
      CidrBlock: !Select
        - 3
        - !Ref SNcidrs
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sn2priv"

  VPCigw:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-igw"

  IGWattach:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref VPCigw
      VpcId: !Ref VPC

  RouteTablePub:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-pub"

  RouteTablePriv1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-priv1"

  RouteTablePriv2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-priv2"

  PubRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref VPCigw
      RouteTableId: !Ref RouteTablePub

  PrivRoute1:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      InstanceId: !Ref NATinstance1
      RouteTableId: !Ref RouteTablePriv1

  PrivRoute2:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      InstanceId: !Ref NATinstance2
      RouteTableId: !Ref RouteTablePriv2

  Subnet1RTassocPub:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePub
      SubnetId: !Ref Subnet1pub

  Subnet1RTassocPriv:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePriv1
      SubnetId: !Ref Subnet1priv

  Subnet2RTassocPub:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePub
      SubnetId: !Ref Subnet2pub

  Subnet2RTassocPriv:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePriv2
      SubnetId: !Ref Subnet2priv

  # NATinstance1:
  #   Type: "AWS::EC2::Instance"
  #   Properties:
  #     AvailabilityZone: !GetAtt Subnet1pub.AvailabilityZone
  #     ImageId: !Ref NATimage
  #     InstanceType: "t2.nano"
  #     KeyName: !Ref KeyPair
  #     Monitoring: false
  #     SubnetId: !Ref Subnet1pub
  #     SourceDestCheck: false
  #     SecurityGroupIds:
  #       - !GetAtt NAT1SecGrp.GroupId
  #     Tags:
  #       - Key: Name
  #         Value: !Sub "${AWS::StackName}-nat1"

  # NATinstance2:
  #   Type: "AWS::EC2::Instance"
  #   Properties:
  #     AvailabilityZone: !GetAtt Subnet2pub.AvailabilityZone
  #     ImageId: !Ref NATimage
  #     InstanceType: "t2.nano"
  #     KeyName: !Ref KeyPair
  #     Monitoring: false
  #     SubnetId: !Ref Subnet2pub
  #     SourceDestCheck: false
  #     SecurityGroupIds:
  #       - !GetAtt NAT2SecGrp.GroupId
  #     Tags:
  #       - Key: Name
  #         Value: !Sub "${AWS::StackName}-nat2"

  NAT1SecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${AWS::StackName}-nat1SG"
      GroupDescription: "For the NAT instances"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: !Select
            - 1
            - !Ref SNcidrs
          Description: "Allow passthru traffic"
          IpProtocol: -1

  NAT2SecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${AWS::StackName}-nat2SG"
      GroupDescription: "For the NAT instances"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: !Select
            - 3
            - !Ref SNcidrs
          Description: "Allow passthru traffic"
          IpProtocol: -1

  BHSecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${AWS::StackName}-bhSG"
      GroupDescription: "For the Bastion host"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref BHLBSecGrp
          Description: "Allow ssh from Management IP via the LB"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22

  PrivInstSecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${AWS::StackName}-privSG"
      GroupDescription: "Control access to instances in the private subnets"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref NAT1SecGrp
          Description: "Allow ssh from NAT instance 1"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
        - SourceSecurityGroupId: !Ref NAT2SecGrp
          Description: "Allow ssh from NAT instance 2"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22

Outputs:

  VPCid:
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPC"
  SN1PubId:
    Value: !Ref Subnet1pub
    Export:
      Name: !Sub "${AWS::StackName}-SN1pub"
  SN1PrivId:
    Value: !Ref Subnet1priv
    Export:
      Name: !Sub "${AWS::StackName}-SN1priv"
  SN2PubId:
    Value: !Ref Subnet2pub
    Export:
      Name: !Sub "${AWS::StackName}-SN2pub"
  SN2PrivId:
    Value: !Ref Subnet2priv
    Export:
      Name: !Sub "${AWS::StackName}-SN2priv"
  NAT1:
    Value: !Ref NATinstance1
    Export:
      Name: !Sub "${AWS::StackName}-NAT1"
  NAT2:
    Value: !Ref NATinstance2
    Export:
      Name: !Sub "${AWS::StackName}-NAT2"